// old/src/patient_login.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import logo from "./img/logo.png";
import styles from "./login.module.css";

function PatientLogin() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const [token, setToken] = useState("");
  const navigate = useNavigate();

  const handleLogin = async () => {
    const response = await fetch("http://127.0.0.1:8000/patient-login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ username, password }),
    });
    const data = await response.json();
    if (data.message === "Invalid credentials") {
      console.error("Error:", response.status, response.statusText);
      setMessage("Login failed");
    }
    if (data.message === "Patient login successful") {
      setToken(data.token);
      localStorage.setItem("token", JSON.stringify(data.token));
      navigate("/dashboard");
    }
  };

  const goToCreateAccount = () => {
    navigate("/createaccount");
  };

  return (
    <div className={styles.login_body}>
      <div className={styles.login_content}>
        <img src={logo} className={styles.login_logo} />
        <h1>Patient Login</h1>

        <input
          className={styles.login_userinput}
          type="text"
          placeholder="Username/Patient ID"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
        />

        <input
          className={styles.login_passwordinput}
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />

        <button className={styles.login_submit} onClick={handleLogin}>
          Enter
        </button>

        <button className={styles.login_createAccount} onClick={goToCreateAccount}>
          Create Account
        </button>
      </div>
    </div>
  );
}

export default PatientLogin;

// vue-version/ovis-frontend-vue/src/pages/PatientLogin.vue
<template>
  <div :class="styles.login_body">
    <div :class="styles.login_content">
      <img :src="logo" :class="styles.login_logo" alt="Logo" />
      <h1>Patient Login</h1>

      <input
        :class="styles.login_userinput"
        type="text"
        placeholder="Username/Patient ID"
        v-model="username"
      />

      <input
        :class="styles.login_passwordinput"
        type="password"
        placeholder="Password"
        v-model="password"
      />

      <button
        :class="styles.login_submit"
        @click="handleLogin"
        :disabled="loading"
      >
        {{ loading ? 'Logging in...' : 'Enter' }}
      </button>

      <button :class="styles.login_createAccount" @click="goToCreateAccount">
        Create Account
      </button>

      <p v-if="message" :class="styles.login_message">{{ message }}</p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import logo from '../assets/logo.png'
import styles from './login.module.css'

const username = ref('')
const password = ref('')
const message = ref('')
const loading = ref(false)

const router = useRouter()

const handleLogin = async () => {
  loading.value = true
  try {
    const response = await fetch('http://127.0.0.1:8000/patient-login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: username.value, password: password.value }),
    })

    const data = await response.json()

    if (data.message === 'Invalid credentials') {
      message.value = 'Login failed. Please check your username or password.'
    } else if (data.message === 'Patient login successful') {
      localStorage.setItem('token', JSON.stringify(data.token))
      router.push('/dashboard')
    } else {
      message.value = 'An unexpected error occurred.'
    }
  } catch (error) {
    console.error('Login error:', error)
    message.value = 'Unable to connect to server.'
  } finally {
    loading.value = false
  }
}

const goToCreateAccount = () => {
  router.push('/createaccount')
}
</script>
