// src/quizpage.jsx
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import styles from "./quiz.module.css";
import SideHeader from "./sideheader";
import logo from "./img/logo.png"

function QuizPage() {
  const [questions, setQuestions] = useState([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [progress, setProgress] = useState(0);
  const [answers, setAnswers] = useState([]);
  const [otherInput, setOtherInput] = useState("");
  const navigate = useNavigate();

  useEffect(() => {
    const fetchQuestions = async () => {
      try {
        const response = await fetch("http://127.0.0.1:8000/questions");
        const data = await response.json();
        setQuestions(data.questions);
        setAnswers(Array(data.questions.length).fill(null));
        setProgress((1 / data.questions.length) * 100);
      } catch (error) {
        console.error("Error fetching questions:", error);
      }
    };

    fetchQuestions();
  }, []);

  const handleChoiceClick = (choice) => {
    const updatedAnswers = [...answers];
    updatedAnswers[currentQuestion] = choice;
    setAnswers(updatedAnswers);
    if (choice !== "Other") {
      setOtherInput("");
    }
  };

  const handleOtherInputChange = (e) => {
    setOtherInput(e.target.value);
    const updatedAnswers = [...answers];
    updatedAnswers[currentQuestion] = e.target.value;
    setAnswers(updatedAnswers);
  };

  const handleNextClick = () => {
    if (currentQuestion < questions.length - 1) {
      const next = currentQuestion + 1;
      setCurrentQuestion(next);
      setProgress(((next + 1) / questions.length) * 100);
    }
  };

  const handlePreviousClick = () => {
    if (currentQuestion > 0) {
      const prev = currentQuestion - 1;
      setCurrentQuestion(prev);
      setProgress(((prev + 1) / questions.length) * 100);
    }
  };

  const handleSubmit = () => {
    if (answers.includes(null) || answers.includes("")) {
      alert("Please answer all questions before submitting.");
      return;
    }
    alert("Quiz submitted! Your answers:\n" + JSON.stringify(answers, null, 2));
    navigate("/dashboard");
  };

  return (
    <div className={styles.pageWrapper}>
      <aside className={styles.sidebar}>
        <SideHeader/>
      </aside>

      <div className={styles.fullPage}>
        <header className={styles.pageHeader}>
          <img src={logo} className={styles.logo} alt="logo" />
        </header>

        <div className={styles.quizContainer}>
          {questions.length === 0 ? (
            <p>Loading questions...</p>
          ) : (
            <>
              <div className={styles.questionNumber}>
                QUESTION {currentQuestion + 1}/{questions.length}
              </div>

              <div className={styles.progressBarWrapper}>
                <div className={styles.progressBar}>
                  <div
                    className={styles.progressFill}
                    style={{ width: `${progress}%` }}
                  ></div>
                </div>
                <div className={styles.progressLabel}>{progress.toFixed(0)}%</div>
              </div>

              <div className={styles.questionBox}>
                {questions[currentQuestion].question}
              </div>

              <div className={styles.choicesRow}>
                {questions[currentQuestion].choices.map((choice, index) => (
                  <button
                    key={index}
                    onClick={() => handleChoiceClick(choice)}
                    className={`${styles.choiceButton} ${
                      answers[currentQuestion] === choice ? styles.selected : ""
                    }`}
                  >
                    {choice}
                  </button>
                ))}
              </div>

              {answers[currentQuestion] === "Other" && (
                <input
                  type="text"
                  className={styles.otherInput}
                  placeholder="Enter your answer"
                  value={otherInput}
                  onChange={handleOtherInputChange}
                />
              )}

              <div className={styles.navigationButtons}>
                <button
                  onClick={handlePreviousClick}
                  className={styles.navButton}
                  disabled={currentQuestion === 0}
                >
                  PREVIOUS
                </button>
                {currentQuestion === questions.length - 1 ? (
                  <button
                    onClick={handleSubmit}
                    className={styles.submitButton}
                  >
                    SUBMIT
                  </button>
                ) : (
                  <button
                    onClick={handleNextClick}
                    className={styles.nextButton}
                  >
                    NEXT
                  </button>
                )}
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

export default QuizPage;

// vue-version/ovis-frontend-vue/src/pages/QuizPage.vue
<template>
  <div :class="styles.pageWrapper">
    <aside :class="styles.sidebar">
      <SideHeader />
    </aside>

    <div :class="styles.fullPage">
      <header :class="styles.pageHeader">
        <img :src="logo" :class="styles.logo" alt="logo" />
      </header>

      <div :class="styles.quizContainer">
        <p v-if="questions.length === 0">Loading questions...</p>
        <template v-else>
          <div :class="styles.questionNumber">
            QUESTION {{ currentQuestion + 1 }}/{{ questions.length }}
          </div>

          <div :class="styles.progressBarWrapper">
            <div :class="styles.progressBar">
              <div
                :class="styles.progressFill"
                :style="{ width: progress + '%' }"
              ></div>
            </div>
            <div :class="styles.progressLabel">{{ progress.toFixed(0) }}%</div>
          </div>

          <div :class="styles.questionBox">
            {{ questions[currentQuestion].question }}
          </div>

          <div :class="styles.choicesRow">
            <button
              v-for="(choice, index) in questions[currentQuestion].choices"
              :key="index"
              @click="handleChoiceClick(choice)"
              :class="[styles.choiceButton, isSelected(choice) && styles.selected]"
            >
              {{ choice }}
            </button>
          </div>

          <input
            v-if="shouldShowOtherInput()"
            type="text"
            :class="styles.otherInput"
            placeholder="Enter your answer"
            v-model="otherInputs[currentQuestion]"
            @input="handleOtherInputChange"
          />

          <div :class="styles.navigationButtons">
            <button
              @click="handlePreviousClick"
              :disabled="currentQuestion === 0"
              :class="styles.navButton"
            >
              PREVIOUS
            </button>
            <button
              v-if="currentQuestion === questions.length - 1"
              @click="handleSubmit"
              :class="styles.submitButton"
            >
              SUBMIT
            </button>
            <button
              v-else
              @click="handleNextClick"
              :class="styles.nextButton"
            >
              NEXT
            </button>
          </div>
        </template>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import logo from '../assets/logo.png'
import styles from './quiz.module.css'
import SideHeader from './SideBar.vue'

const router = useRouter()

const questions = ref([])
const currentQuestion = ref(0)
const progress = ref(0)
const answers = ref([])
const otherInputs = ref({})

onMounted(async () => {
  try {
    const response = await fetch('http://0.0.0.0:8000/getquestions')
    const data = await response.json()
    questions.value = data.questions
    answers.value = Array(data.questions.length).fill([])
    progress.value = (1 / data.questions.length) * 100
  } catch (error) {
    console.error('Error fetching questions:', error)
  }
})

const handleChoiceClick = (choice) => {
  const updated = [...answers.value]
  const current = updated[currentQuestion.value] || []

  if (current.includes(choice)) {
    updated[currentQuestion.value] = current.filter(c => c !== choice)
  } else {
    updated[currentQuestion.value] = [...current, choice]
  }

  answers.value = updated
}

const handleOtherInputChange = () => {
  const inputValue = otherInputs.value[currentQuestion.value]
  const updatedAnswers = [...answers.value]
  const updatedOtherInputs = { ...otherInputs.value }

  updatedOtherInputs[currentQuestion.value] = inputValue
  const filtered = (updatedAnswers[currentQuestion.value] || []).filter(
    a => !a.startsWith('Other:')
  )
  updatedAnswers[currentQuestion.value] = [...filtered, `Other: ${inputValue}`]

  answers.value = updatedAnswers
  otherInputs.value = updatedOtherInputs
}

const isSelected = (choice) => {
  return (answers.value[currentQuestion.value] || []).includes(choice)
}

const shouldShowOtherInput = () => {
  return (answers.value[currentQuestion.value] || []).some(a =>
    a.toLowerCase().includes('other')
  )
}

const handleNextClick = () => {
  if (currentQuestion.value < questions.value.length - 1) {
    currentQuestion.value++
    progress.value = ((currentQuestion.value + 1) / questions.value.length) * 100
  }
}

const handlePreviousClick = () => {
  if (currentQuestion.value > 0) {
    currentQuestion.value--
    progress.value = ((currentQuestion.value + 1) / questions.value.length) * 100
  }
}

const handleSubmit = async () => {
  if (answers.value.some(a => !Array.isArray(a) || a.length === 0)) {
    alert('Please answer all questions before submitting.')
    return
  }

  const token = JSON.parse(localStorage.getItem('token'))
  const userId = token?.name || 'anonymous'

  try {
    const response = await fetch('http://127.0.0.1:8000/submit', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ user_id: userId, answers: answers.value }),
    })

    if (response.ok) {
      alert('Quiz submitted successfully!')
      router.push('/dashboard')
    } else {
      alert('Submission failed. Please try again.')
    }
  } catch (err) {
    console.error('Error during submission:', err)
    alert('An error occurred while submitting.')
  }
}
</script>
