// vue-version/ovis-frontend-vue/src/pages/AdminDashboard.vue
<template>
  <div :class="styles.dashboard">
    <h1 :class="styles.title">Admin Dashboard</h1>
    <h2 :class="styles.subtitle">Patients by Doctor</h2>
    <div
      v-for="patient in patients"
      :key="patient.username"
      :class="styles.patientBlock"
    >
      <button
        :class="styles.patientLink"
        @click="goToPatient(patient.username)"
      >
        {{ patient.name }} {{ patient.username }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import styles from './adminDashboard.module.css'

const patients = ref([])
const router = useRouter()

const fetchPatients = async () => {
  const token = JSON.parse(localStorage.getItem('token'))
  const doctor = token?.name || 'Unknown'

  try {
    const storedToken = JSON.parse(localStorage.getItem('token')).access_token
    const res = await fetch(`http://127.0.0.1:8000/admin/patients`, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        'Authorization': `Bearer ${storedToken}`
      }
    })
    const data = await res.json()
    patients.value = data.patients
  } catch (err) {
    console.error('Failed to fetch patients:', err)
  }
}

const goToPatient = (username) => {
  router.push(`/admin/patient/${username}`)
}

onMounted(() => {
  fetchPatients()
})
</script>

// src/admin_dashboard.jsx
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import styles from "./adminDashboard.module.css";

function AdminDashboard() {
  const [patients, setPatients] = useState([]);
  const navigate = useNavigate();

  useEffect(() => {
    const token = JSON.parse(localStorage.getItem("token"));
    const doctor = token?.name || "Unknown";

    const fetchPatients = async () => {
      try {
        const res = await fetch(`http://127.0.0.1:8000/admin/patients?doctor=${encodeURIComponent(doctor)}`);
        const data = await res.json();
        setPatients(data.patients);
      } catch (err) {
        console.error("Failed to fetch patients:", err);
      }
    };

    fetchPatients();
  }, []);

  return (
    <div className={styles.dashboard}>
      <h1 className={styles.title}>Admin Dashboard</h1>
      <h2 className={styles.subtitle}>Patients by Doctor</h2>
      {patients.map((patient) => (
        <div key={patient.username} className={styles.patientBlock}>
          <button
            className={styles.patientLink}
            onClick={() => navigate(`/admin/patient/${patient.username}`)}
          >
            {patient.name} ({patient.username})
          </button>
        </div>
      ))}
    </div>
  );
}

export default AdminDashboard;
