// vue-version/ovis-frontend-vue/src/pages/AdminPatientLookup.vue
<template>
  <div :class="styles.dashboard">
    <h1 :class="styles.title">Quiz Submissions for {{ username }}</h1>

    <p v-if="answers.length === 0">No submissions found.</p>

    <ul v-else :class="styles.quizList">
      <li
        v-for="(entry, index) in answers"
        :key="index"
        :class="styles.quizItem"
      >
        <div>
          <strong>Time:</strong>
          <span :class="styles.timestamp">
            {{ formatTimestamp(entry.timestamp) }}
          </span>
        </div>
        <div><strong>Answers:</strong></div>
        <ul class="answerList">
            <li
                v-for="(answerGroup, i) in entry.answers"
                :key="i"
                class="answerItem"
            >
                {{ answerGroup[0] }}
            </li>
        </ul>

      </li>
    </ul>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import styles from './adminDashboard.module.css'

const route = useRoute()
const username = route.params.username
const answers = ref([])

const fetchAnswers = async () => {
  try {
    const res = await fetch(`http://0.0.0.0:8000/admin/answers?user_id=${username}`)
    const data = await res.json()
    answers.value = data.answers
  } catch (err) {
    console.error('Error fetching patient answers:', err)
  }
}

const formatTimestamp = (timestamp) => {
  return new Date(timestamp).toLocaleString()
}

onMounted(() => {
  fetchAnswers()
})
</script>

// src/admin_patient_lookup.jsx
import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import styles from "./adminDashboard.module.css"; // reuse styles

function AdminPatientLookup() {
  const { username } = useParams();
  const [answers, setAnswers] = useState([]);

  useEffect(() => {
    const fetchAnswers = async () => {
      try {
        const res = await fetch(`http://127.0.0.1:8000/admin/answers/${username}`);
        const data = await res.json();
        setAnswers(data.answers);
      } catch (err) {
        console.error("Error fetching patient answers:", err);
      }
    };

    fetchAnswers();
  }, [username]);

  return (
    <div className={styles.dashboard}>
      <h1 className={styles.title}>Quiz Submissions for {username}</h1>
      {answers.length === 0 ? (
        <p>No submissions found.</p>
      ) : (
        <ul className={styles.quizList}>
          {answers.map((entry, index) => (
            <li key={index} className={styles.quizItem}>
              <div>
                <strong>Time:</strong>{" "}
                <span className={styles.timestamp}>
                  {new Date(entry.timestamp).toLocaleString()}
                </span>
              </div>
              <div><strong>Answers:</strong></div>
              <ul className={styles.answerList}>
                {entry.answers[0].map((ans, i) => (
                  <li key={i} className={styles.answerItem}>– {ans}</li>
                ))}
              </ul>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

export default AdminPatientLookup;
