// vue-version/ovis-frontend-vue/src/pages/Dashboard.vue
<template>
  <div :class="styles.dashboard">
    <aside :class="styles.sidebar">
      <Sidebar />
    </aside>

    <main :class="styles.mainContent">
        <header :class="styles.topHeader">
            <div :class="styles.headerActions">
                <div :class="styles.iconWithBadge">
                <i class="fas fa-bell"></i>
                <span :class="styles.badgeRed">5</span>
                </div>

                <div :class="styles.iconWithBadge">
                <i class="fas fa-comment-dots"></i>
                <span :class="styles.badgeGreen">3</span>
                </div>

                <div :class="styles.profileDropdown">
                <img :src="userAvatar" :class="styles.avatar" />
                <template v-if="patient">
                  {{patient.username}}
                </template>
                <p v-else>Loading...</p>
                <button @click="signOut">▼</button>
                </div>
            </div>
        </header>


      <section :class="styles.contentGrid">
        <div :class="[styles.card, styles.personalBox]">
          <h2>Personal Data</h2>
          <template v-if="patient">
            <p><strong>Name:</strong> {{ patient.name }}</p>
            <p><strong>DoB:</strong> {{ patient.dob }}</p>
            <p><strong>Sex:</strong> {{ patient.sex }}</p>
          </template>
          <p v-else>Loading...</p>
        </div>

        <div :class="[styles.card, styles.streakBox]">
          <h2>Current Streak</h2>
          <p> {{ currentStreak }} day{{ currentStreak === 1 ? '' : 's' }}</p>
          <div :class="styles.progressBarContainer">
            <div
              :class="styles.progressBarFill"
              :style="{ width: getProgressPercent(currentStreak) + '%' }"
            ></div>
          </div>
          <p>{{ getDaysToNextReward(currentStreak) }} day{{ getDaysToNextReward(currentStreak) !== 1 ? 's' : '' }} to next reward</p>
        </div>

        <div :class="[styles.card, styles.loggerBox]">
          <h2>Daily Logger</h2>
          <p>{{ today }}</p>
          <button @click="goToQuiz">Begin</button>
        </div>
      </section>
    </main>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import logo from '../assets/logo.png'
import Sidebar from './Sidebar.vue'
import styles from './dashboard.module.css'

const router = useRouter()

const patient = ref(null)
const currentStreak = ref(0)
const rewardInterval = 5

const today = new Date().toLocaleDateString('en-US', {
  year: 'numeric',
  month: 'long',
  day: 'numeric'
})

const fetchPatient = async () => {
  try {
    const storedToken = JSON.parse(localStorage.getItem('token')).access_token
    const response = await fetch('http://0.0.0.0:8000/userinfo', {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        'Authorization': `Bearer ${storedToken}`
      }
    })

    const data = await response.json()
    patient.value = {
      name: data.full_name,
      dob: data.dob,
      sex: data.sex,
      username: data.username
    }
  }catch (error) {
    console.error(error)
  }
}

const fetchStreak = async () => {
  try {
    const token = JSON.parse(localStorage.getItem('token'))
    const response = await fetch(`http://127.0.0.1:8000/getstreak?username=${token.name}`)
    const data = await response.json()
    currentStreak.value = data
  } catch (err) {
    console.error('Failed to load streak', err)
  }
}

onMounted(() => {
  fetchPatient()
  fetchStreak()
})

const getProgressPercent = (count) => {
  const progress = count % rewardInterval
  return (progress / rewardInterval) * 100
}

const getDaysToNextReward = (count) => {
  const remaining = rewardInterval - (count % rewardInterval)
  return remaining === rewardInterval ? 0 : remaining
}

const goToQuiz = () => {
  router.push('/quiz')
}

const userAvatar = 'https://via.placeholder.com/40' // replace with your own image

const signOut = () => {
  // Clear token and redirect to login
  localStorage.removeItem('token')
  window.location.href = '/patientlogin'
}

</script>

// src/dashboard.jsx
import React, { useEffect, useState } from "react";
import styles from "./dashboard.module.css";
import { useNavigate } from "react-router-dom";
import SideHeader from "./sideheader";
import logo from "./img/logo.png"

function DashboardPage() {
  const [patient, setPatient] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchPatient = async () => {
      try {
        const token = JSON.parse(localStorage.getItem("token"));
        const response = await fetch(`http://127.0.0.1:8000/personalinfo?id=${token.name}`, {
          method: "GET",
          headers: { "Content-Type": "application/json" },
        });
        const data = await response.json();
        setPatient(data);
      } catch (error) {
        console.error("Error fetching patient info:", error);
      }
    };

    fetchPatient();
  }, []);

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric"
  });

  return (
    <div className={styles.pageWrapper}>
      <aside className={styles.sidebar}>
        <SideHeader/>
      </aside>

      <div className={styles.mainContent}>
        <header className={styles.pageHeader}>
          <img src={logo} className = {styles.logo}/>
        </header>

        <div className={styles.contentGrid}>
          <div className={styles.personalBox}>
            <h2>Personal Data</h2>
            {patient ? (
              <>
                <p><strong>Name:</strong> {patient.name}</p>
                <p><strong>DoB:</strong> {patient.dob}</p>
                <p><strong>Sex:</strong> {patient.sex}</p>
                <p><strong>System:</strong> {patient.condition}</p>
                <p><em>{patient.notes}</em></p>
              </>
            ) : (
              <p>Loading personal data...</p>
            )}
          </div>

          <div className={styles.loggerBox}>
            <div className={styles.loggerHeader}>
              <div className={styles.loggerTitle}>Daily Logger</div>
              <div className={styles.loggerStatus}>Complete ✅</div>
            </div>

            <div className={styles.loggerContent}>
            <div className={styles.loggerDate}>{today}</div>
            <button className={styles.enterButton} onClick={() => navigate("/quiz")}>Enter</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default DashboardPage;
