// vue-version/ovis-frontend-vue/src/pages/MainPage.vue
<template>
  <div :class="styles.main_body">
    <div :class="styles.main_header">
      <img :src="logo" :class="styles.main_logo" />
    </div>

    <div :class="styles.main_MainPage">
      <div :class="styles.main_leftblank"></div>

      <div :class="styles.main_content">
        <RouterLink to="/patientlogin">
          <button :class="styles.main_button">Patient Login</button>
        </RouterLink>
        <RouterLink to="/adminlogin">
          <button :class="styles.main_button">Admin Login</button>
        </RouterLink>
        <RouterLink to="/faq">
          <button :class="styles.main_button">FAQ</button>
        </RouterLink>
      </div>

      <div :class="styles.main_rightblank"></div>
    </div>
  </div>
</template>

<script setup>
import { useRouter } from 'vue-router';
import styles from './MainPage.module.css';
import logo from '../assets/logo.png';

const router = useRouter();

const handleClick = () => {
  router.push('/dashboard');
};
</script>

// src/MainPage.jsx
import React from "react";
import { Link, useNavigate} from "react-router-dom";
import styles from "./MainPage.module.css"
import logo from "./img/logo.png"

function MainPage() {
    const navigate = useNavigate();
    const handleClick = () => {
        navigate('/dashboard'); // redirect to another route
      };
    return (
        <div className={styles.main_body}>
            <div className={styles.main_header}>
                <img src={logo} className = {styles.main_logo}/>
            </div>

            <div className={styles.main_MainPage}>
                <div className={styles.main_leftblank}>
                    
                </div>

                <div className={styles.main_content}>
                    <Link to="/patientlogin">
                        <button className={styles.main_button}>
                            Patient Login
                        </button>
                    </Link>
                    <Link to="/adminlogin">
                        <button className={styles.main_button}>
                            Admin Login
                        </button>
                    </Link>
                    <Link to="/faq">
                        <button className={styles.main_button}>
                            FAQ
                        </button>
                    </Link>
                </div>

                <div className={styles.main_rightblank}>
                    
                </div>
            </div>
        </div>
    );
  }

export default MainPage
